### ISSUE TITLE
Perruchet Effect review

### ISSUE THREAD

**Issue by earcanal** [ajwills72/rminr#22]
I found this easy to follow.

- [x] Explain that this is a conditioning experiment before abbreviating CS and US?
- [x] Present IVs, DVs and predictions using bullets so it's easy to see the design at a glance?
- [x] osfr is now installed, so don't need install.packages('osfr')
- [x] Based on workshop experience of terrible project and file naming, I've been suggesting names e.g. create a project named 'perruchet'
- [x] Say that you only need to do the downloading from OSF once, so run those commands in the console
- [x] As per above, my pattern is along the lines of 'Create a script named perruchet.r and add the code as you progress through the worksheet.'
- [x] I've been including "section comments" in markdown blocks, to help people who copy-paste the block into a script e.g. # apply exclusion criteria
- [x] maybe say that a function doesn't do anything until you call it?
- [x] In "Adding a second dependent variable" I think it should read "Finally, we select the subject, trial, and value columns of that dataframe, and place it into expect."
- [x] maybe say that the second loop takes a while to run due to the amount of data it needs to process
- [x] Do you want to factor the generic description of log transformation out into "Data preprocessing for scales" and link to it in the remaining (specific) GSR transformation or do you trust me to do that? I haven't got to the other pipelines that do log transformation yet.
- [x] When I got to "Removing trials" I was confused about how the run length was calculated. Was that done in the experiment?
- [x] If they have rminr-data, they can source("../rminr-data/themeapa.R"). Also source("themeapa.R") is duplicated.

## typos

- [x]  "not do this combination"
- [x]  "at that six participants missed"
- [x]  "Ignoring the first and the last three lines for a moment," (last 2 lines?)
- [x]  "When then add a new column"
- [x]  "(once for each GSR recording, so 20 times a second. We"
- [x]  "and the following trial there will not be a sound"
- [x]  "This graph is a bit more complex than the ones we’ve produce before,"
- [x]  "First, graph a copy of the themeapa.R file"

**Comment by ajwills72** [comment]
The main open issue:

- Yes, please extract out log transform -- but I'd say that's more for the 'experiments' peprocessing worksheet, rather than the scales one?

Issues I closed without doing anything:

- I felt the IVs/DVs were clear as is.

- Best not to have any part of your pipeline pasted to the console, then there's no record. If something only needs to be run once, say that in a comment (or write some fancy code to detect if it's already been run - but that's not the right approach for this tutorial).

- I rediscovered that I'd put themeapa on my website. That's the easiest approach.

-  "not do this combination" - can't see the problem here

**Comment by ajwills72** [comment]
All done here I think :-)
