### ISSUE TITLE
The effects of negative mental imagery on self-esteem

### ISSUE THREAD

**Issue by earcanal** [ajwills72/rminr#24]
[This worksheet](../blob/master/src/cs-self-esteem.Rmd) has the following outstanding issues:

- [x] Do the alpha calculations match Sophie's?
- [x] If so, what should we say about the low values?
- [x] According to Heatherton & Polivy (1991), the SSES has "Performance", "Social" and "Appearance" subscales . As we've advised students not to calculate a total score for a scale with subscales, I'm not sure what to do at this point in the worksheet.

Should we stop at `Comparing interventions` or do compare some conditions (I'm not sure what the hypotheses were in this experiment) and discuss what to do about the possible baseline differences e.g.

## Pairwise comparisons

Given the interaction, we would might want to make [pairwise comparisons](anova1.html#pairs), to compare the imagery conditions against the control condition, and against each other...

## Controlling for baseline differences

To address the difference in baseline scores, we could run the same ANOVA on the _difference_ between the pre and post scores, or we could include the baseline score as a covariate in an ANCOVA...

**Comment by ajwills72** [comment]
- I was surprised to see that this was a Ph.D. experiment; the intention was that this would be an UG dissertation. Let's leave it now, but please make sure the rest are actually UG dissertations. 

- I can't comment on whether the measures match Sophie's, of course :-)

- Overall, I think you probably do need Sophie's input because in the below I'm having to guess a  bunch of stuff about her intentions in this project. But, some thoughts in case they are helpful:

- What does one say about the low values ? You say that they are low, and that's not a good thing. Not much else you can say, I think?

- Subscales: Don't do it in this worksheet. The point here, presumably, is to compare the alpha with the reported alpha for the SSES. This is on the whole scale. So do that calculation. 

- More generally, whether you do the whole scale or the subscales depends on your research question. If you're treating SSES as a single construct (i.e. people have so much self-esteem at a particular point and you can put a single number on it) then you do the alpha on the whole thing, of course. If you have a questionnaire that you intend to measure different things with (like depression AND anxiety AND stress) then you look at the alpha for those three things, right?

- The following applies to the previous worksheet also - you shouldn't be calculating alpha on a data set that contains both pre- and post- intervention measures. This is because you then have two results from each participant, which is against the assumptions of the test, and will also likely lead to a mis-estimation of alpha (well, is pretty much guaranteed to if the experimental manipulation works.

- Yes, do pairwise comparisons. Yes, you will need to know what the hypotheses were to pick the right ones. I of course do not know this.

- I would have expected to see a graph of some sort for the data going into the mixed ANOVA.

- You seem to be missing a crucial step: bf[4]/bf[3]

- Controlling for baseline differences: Do not do this in addition to your other analyses, it adds nothing to the analyses you have already conducted. An interaction *is* an effect on the differences. ANCOVA would not add anything here, either.

- That said, the simplest analysis here is to calculate the difference scores, and do a one-way b/subj ANOVA. It would be possible to report that and not report a factorial ANOVA. The whole reason for collecting pre scores is to allow for correction of pre-exisiting differences (otherwise we'd just collect post scores). The interaction doesn't really represent any likely hypothesis for this study. 

- The test on the pre-scores. Presumably, the original experiment did NHST and p > .05 so they concluded there were no differences? This conclusion is of course a logical fallacy, and the Bayesian analysis reveals this.

**Comment by earcanal** [comment]
This is the only non-undergraduate case study. The data were chosen primarily as the basis for the preprocessing and analysing scales worksheets (before we decided to sample undergraduate projects for case studies).

- [ ] Exclude post-intervention measures before calculating alpha
- [ ] Show `bf[4]/bf[3]` calculation for interaction
- [ ] Decide whether to do 1-way b/subj ANOVA on pre-post differences, or factorial ANOVA
- [ ] Graph data before ANOVA
- [ ] Compare alpha against Sophie's calculations
- [ ] Do pairwise comparisons based on Sophie's hypotheses

**Comment by ajwills72** [comment]
Worksheet marked as completed on our project kanban, so closing this issue.
