### ISSUE TITLE
Completing "Preprocessing experiments"

### ISSUE THREAD

**Issue by earcanal** [ajwills72/rminr#28]
This worksheet now contains all of the items that seem to fit with the title (c7c7b91123c4cacd8192a0b5e369e2d4bdfc2b53). I excluded "inverse transformation", as I checked my notes and Helen, and I decided not to transform the data in her case study.

* Does this worksheet need additional sections? If so, can you think of any candidates?
* What exercises would be appropriate?

That should be all I need to get this ready for review.

**Comment by ajwills72** [comment]
Cool.

On additional sections - this should be driven by your work on the dissertation worksheets. If none of the projects you've looked at need more than this, then this is all we'll include. If there are other things, include them.

On exercise - For what you have so far, I suggest a single long-ish exercise. What I suggest here is that you find or generate some data that would allow the students to practice de-duplication, exclusion on the basis of a calculated criterion, and some kind of transform (perhaps something other than a log transform e.g. the inverse transform you mention), on a new data set. One that would not allow them to cut and paste what they've already done in the worksheet, but would required some level of understanding of how to apply these operations to new data.

**Comment by earcanal** [comment]
I used `RNOmni::rankNorm()` for the example as reciprocal and square root transformations didn't seem to offer anything that a log transformation would do. I've asked Helen Lloyd if this is the transformation she applied to NA in her PANAS data.

If this is OK, it would require installation of `RNOmni`.

**Comment by ajwills72** [comment]
No, let's not introduce a new package and a really really obscure (in psychology) transformation that's mainly intended as an alternative to non-parametric statistics. It's just an exercise, so the goal is that they learn the key concepts and are unable to just cut-and-pate. Telling them to do a reciprocal transformation (1/x) or a square root, is a good choice, not because its fundamentally different to a log transform but because it means they can't cut and paste.

I couldn't get any further with reviewing this worksheet because the PANAS data is not present in the repo, so I can't recompile the Rmd. Moving this back to 'With Paul' on src/kanban.md
