### ISSUE TITLE
Suggested updates to Absolute Beginners' Guide to R

### ISSUE THREAD

**Issue by benwhalley** [ajwills72/rminr#34]
Hi Andy - this is not super-urgent, but am putting it here to make sure it doesn't get lost.  I am also going to send this to the TARAs from 519 to make sure I've captured everything.

-----------------

We have had _lots_ of issues in PSYC519/719 this year related to projects and use of scripts and the TARAs and I are keen to makes some changes to these pages to ensure students get off on the right foot next year. 

We have spent so many hours fixing small issues related to basic use of Rstudio this is actually pretty high priority — even though the changes might seem quite small.

The big problems have been:

- Students don't create projects (sigh)
- Students create too many projects (e.g. one each week)
- Students type or paste code into the console (which leads to multiple issues as they progress to multi line commands)
- Students don't use R script files. When asked, it's because they have got used to pasting into the console, and are resistant to changing what they do (this leads to self inflicted problems, especially for multi line tidyverse commands, but nevertheless increases support headaches). I would guess this affects about 30-50% of students starting PSYC519

In discussion, we agreed we'd like to:

- Add emphasis in the using_rstudio.md file to make clear only 1 project needed per MODULE. It current hints at this, but it needs hammering home. Students also requested we post videos of some of the basic tasks like this which I have recorded and which we could include. 

- Don't teach people to paste into the console at all... we want to get them running R scripts right away to avoid having to explain and switch them across later.  See below for files affected

- Add a strong recommendation to use Firefox. This has solved many issues — I think in part because students end up with old versions of Chrome or Safari so just installing anything new helps. Updating is harder to verify (and impossible with Safari without an OS update)  and I'm loathe to recommend Chrome to anyone, so I think this is the best option.

- Teach the keyboard shortcuts for running a line of code (ctrl+enter) early on... we find this makes the students so much faster. These should be added to a new "how to run a line of code from a s script file" worksheet which would follow the "using projects" page. Although this does increase the startup time a little bit I think it would be a big win for productivity later... and it turns out to be hard to introduce this later because they get stuck in habits early on.

I could make these changes over the summer, but my suggestion would be to give this to Paul as another discrete task if we can get the money to pay him. He'd do a better/more thorough job than me in any case.

Files touched: A quick ack/grep suggests these files contain a reference to the console so might get touched in the update:

```
docs/sample.html
docs/non-parametric.html
docs/lions.html
docs/irr.html
docs/navigate.html
docs/modmark.html
docs/chi.html
docs/more-on-kappa.html
docs/vbg_evidence.html
docs/chi-extended.html
docs/using-projects.md
docs/vbg_corr.html
src/navigate.Rmd
src/non-parametric.Rmd
```

**Comment by ajwills72** [comment]
Hi Ben,

I couldn't find where you'd put this on github, it's not logged as an issue, and I couldn't find it anywhere else. Yet the email looks like it came from github so I'm guessing it must be somewhere?

VBGR already does projects from the outset - I don't think you'll find any references to doing things in the console in the four worksheets. Not sure exactly what grep you did, but all VBGR files begin vbg_ . You list one of those below, it's a follow on from the previous worksheet, it specifically references projects right at the top.

Not that I'm denying there seems to be an issue with students using the console, it's just that VBGR can't be the source.

The likely source is a decision I took in PSYC411 back in 2017 to do some stuff in the console first so there was less to learn before the got some output. They use the console for a grand total of 3 hours before being introduced to projects in hour 4 and then all subsequent material directs them to use projects, I believe (if you spot something that uses the console after Absolute Beginners' section, Evidence worksheet, let me know). "Using RStudio projects" also specifically mentions CTRL+ENTER.

It's interesting this first 3 hours of experience is so formative that you're still feeling the effects in PSYC519. I will look to see what I can do to the Absolute Beginners' guide in this regard over the summer, but it'll have to be re-ordering of material rather than substantial expansion - there just isn't time for expansion in the four hours they have in PSYC411 to both learn R from scratch and complete analysis of an experiment.

But I think re-arranging the first three hours will probably be enough.

Cheers

Andy

________________________________

**Comment by benwhalley** [comment]
Hi Andy - I can see the issue at: https://github.com/ajwills72/rminr/issues/34

Weird that I hadn't twigged that the VBGR doesn't suggest using the console. I think I just assumed it did because so many students do it. I know quite a few have been going back to the Stage 1 materials too because they feel like they didn't quite 'get' it from the initial worksheets so wanted more practice, so perhaps it's that.

For ref, the grep I did used this pattern `(?<!icon-)console` to filter out some files positives on files in the src and docs directory of this repo. For example and number of files (exploring-incomes.rmd, group-differences.Rmd) contain a phrase something like this:

> **Type (or copy and paste) the command in the grey box into the _Console_ window of RStudio, and press the RETURN key.**

**Comment by ajwills72** [comment]
Yeah, appearing now - weird, was not there last night for sure. Weird github bug I guess, now resolved.

Thanks for further grep info - useful. I'm reasonably sure such phrases only appear in the worksheets up to and including 'Evidence' - which are the first 3 hours of material. Do let me know if you find stuff later than that, though.

I'll assign to me as a task to update those early sheets in the way you suggest.

**Comment by ajwills72** [comment]
These issues have been addressed in the 2021 edition, just gone live today.
